apiVersion: v1
kind: Service

metadata:
  name: django-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer

  selector:
    app: django-app

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000